import { style } from './dom';

export default style({
  bg_color_black: ['backgroundColor', 'black'],
  bg_color_grey: ['backgroundColor', 'grey'],
  bg_color_white: ['backgroundColor', 'white'],
  color_black: ['color', 'black'],
  color_white: ['color', 'white'],
  cursor_pointer: ['cursor', 'pointer'],
  display_none: ['display', 'none'],
  fs_l: ['fontSize', '18px'],
  fs_m: ['fontSize', '16px'],
  fs_xl: ['fontSize', '24px'],
  grid_template_columns_auto: ['gridTemplateColumns', 'auto'],
  grid_template_columns_max_content: ['gridTemplateColumns', 'max-content'],
  grid_template_rows_max_content: ['gridTemplateRows', 'max-content'],
  grid: ['display', 'grid'],
  grid_auto_flow_column: ['gridAutoFlow', 'column'],
  grid_gap_m: ['gridGap', '10px'],
  grid_gap_l: ['gridGap', '20px'],
  height_100: ['height', '100%'],
  margin_0: ['margin', '0px'],
  padding_0: ['padding', '0px'],
  padding_m: ['padding', '5px'],
  padding_l: ['padding', '10px'],
  padding_xl: ['padding', '15px'],
  text_strike: ['textDecoration', 'line-through'],
});
